name: Deploy Laravel to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4
      
      # Setup PHP untuk Laravel
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite, curl, zip, xml
          tools: composer:v2
      
      # Install dependensi PHP
      - name: Install dependensi PHP
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      
      # Konfigurasi Laravel
      - name: Konfigurasi Laravel
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          sed -i 's/APP_ENV=local/APP_ENV=production/g' .env
          sed -i 's/APP_DEBUG=true/APP_DEBUG=false/g' .env
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/g' .env
          sed -i '/DB_HOST=/d' .env
          sed -i '/DB_PORT=/d' .env
          sed -i '/DB_DATABASE=/d' .env
          sed -i '/DB_USERNAME=/d' .env
          sed -i '/DB_PASSWORD=/d' .env
          echo "DB_DATABASE=database/database.sqlite" >> .env
          mkdir -p database
          touch database/database.sqlite
          php artisan key:generate
      
      # Setup Node.js untuk asset building
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      # Install dan build frontend assets
      - name: Install & build frontend
        run: |
          npm ci
          npm run build
      
      # Konfigurasi GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      # Persiapkan konten statis dengan pemeriksaan rinci
      - name: Persiapkan konten statis
        run: |
          # Buat direktori untuk konten statis
          mkdir -p _site
          
          # Buat file .nojekyll untuk menonaktifkan Jekyll
          touch _site/.nojekyll
          
          # Salin semua file dari public ke _site
          cp -r public/* _site/
          
          # PENTING: Pastikan ada index.html di root
          echo "Membuat index.html statis..."
          
          # Jalankan server PHP dan ambil konten halaman utama
          php -S localhost:8000 -t public &
          SERVER_PID=$!
          
          # Tunggu server siap
          sleep 5
          
          # Verifikasi server berjalan
          curl -v http://localhost:8000/ || echo "Peringatan: Tidak dapat terhubung ke server Laravel"
          
          # Ambil konten halaman utama ke index.html
          curl -L -s http://localhost:8000/ > _site/index.html
          
          # Periksa ukuran file index.html
          ls -l _site/index.html
          
          # Jika file terlalu kecil, buat file minimal
          if [ ! -s "_site/index.html" ] || [ $(stat -c%s "_site/index.html") -lt 100 ]; then
            echo "Membuat index.html fallback minimal..."
            cat > _site/index.html << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laravel 12 CRUD</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        .container { max-width: 800px; margin: 0 auto; }
        h1 { color: #333; }
        .note { background: #f8f9fa; padding: 15px; border-left: 4px solid #007bff; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Laravel 12 CRUD Application</h1>
        <div class="note">
            <p>This is a static version of a Laravel 12 application hosted on GitHub Pages.</p>
            <p>Note that GitHub Pages only supports static content, so full Laravel functionality is not available.</p>
        </div>
        <p>Please check the <a href="https://github.com/wawanwfs/Laravel-12-CRUD">repository</a> for the complete project.</p>
    </div>
    <script>
        // Redirect ke halaman utama jika ada path redirect tersimpan
        const redirectPath = sessionStorage.getItem('redirect_path');
        if (redirectPath) {
            console.log('Redirected from:', redirectPath);
            sessionStorage.removeItem('redirect_path');
            // Tambahkan logika penanganan router di sini jika diperlukan
        }
    </script>
</body>
</html>
EOF
          fi
          
          # Matikan server PHP
          kill $SERVER_PID || true
          
          # Buat file 404.html untuk SPA routing
          cat > _site/404.html << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page Not Found</title>
    <script>
        // Simpan path saat ini untuk routing SPA
        const currentPath = window.location.pathname;
        sessionStorage.setItem('redirect_path', currentPath);
        
        // Redirect ke halaman utama dengan mempertimbangkan base path repo
        window.location.href = '/Laravel-12-CRUD/';
    </script>
    <style>
        body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
        h1 { color: #333; }
        .message { margin: 30px 0; }
    </style>
</head>
<body>
    <h1>404 - Page Not Found</h1>
    <div class="message">
        <p>The page you're looking for doesn't exist or has been moved.</p>
        <p>Redirecting to homepage...</p>
    </div>
</body>
</html>
EOF
          
          # Tampilkan struktur direktori final untuk debugging
          echo "=== Struktur direktori _site ==="
          find _site -type f | sort
      
      # Upload artifact untuk deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
