name: Deploy Laravel to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Memungkinkan untuk menjalankan workflow secara manual dari tab Actions
  workflow_dispatch:

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode repository
      - uses: actions/checkout@v3

      # Setup PHP dengan versi yang sesuai untuk Laravel 12
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4.5"
          extensions: mbstring, dom, fileinfo, mysql, gd, curl, zip, xml
          tools: composer:v2

      # Install dependensi Composer
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      # Setup Node.js untuk kompilasi aset (jika menggunakan Vite/Laravel Mix)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependensi Node.js
      - name: Install Node Dependencies
        run: npm install

      # Build aset frontend
      - name: Build Assets
        run: npm run build

      # Generate application key
      - name: Generate Application Key
        run: php artisan key:generate --force

      # Optimasi Laravel
      - name: Optimize Laravel
        run: |
          php artisan optimize
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # Buat direktori build dan kopikan konten public ke dalamnya
      - name: Prepare Build Directory
        run: |
          mkdir -p build
          cp -R public/* build/
          cp public/.htaccess build/ || true
          # Buat file index.php yang mengarah ke folder public
          echo '<?php include_once("index.html");' > build/index.php

      # Buat file .nojekyll untuk menghindari pemrosesan Jekyll
      - name: Create .nojekyll file
        run: touch build/.nojekyll

      # Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: true
